name: Laravel

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  laravel-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Install envoyer
      run: composer global require laravel/envoy
    - name: Make envoyer executeable
      run: chmod +x ~/.composer/vendor/bin/envoy
    - name: move envoy
      run: ln -s ~/.composer/vendor/bin/envoy /usr/bin/envoy
    - uses: webfactory/ssh-agent@v0.4.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: run envoy
      run: |
        ~/.composer/vendor/bin/envoy run deploy_production

    
